name: intray-api-gen
version: '0.0.0.0'
synopsis: Generators for intray-api
category: Intray
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2018 Tom Sydney Kerckhove'
license: AllRightsReserved
github: NorfairKing/intray
default-extensions:
- NoImplicitPrelude

dependencies:
- base >=4.7 && <5

library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Intray.API.Gen
  - Intray.API.Admin.Gen
  - Intray.API.Protected.Gen
  - Intray.API.Protected.Account.Gen
  - Intray.API.Protected.Item.Gen

  dependencies:
  - QuickCheck
  - bytestring
  - genvalidity
  - genvalidity-bytestring
  - genvalidity-mergeless
  - genvalidity-text
  - genvalidity-time
  - genvalidity-uuid
  - intray-api
  - intray-data
  - intray-data-gen
  - stripe-core
  - stripe-haskell
  - text
  - validity
  - validity-bytestring
  - validity-text
  - validity-time

tests:
  intray-api-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-text
    - hspec
    - intray-api
    - intray-api-gen
    - intray-data
    - intray-data-gen
    - QuickCheck
    - text
    - bytestring
