name: intray-cli
version: '0.0.0.0'
synopsis: A command line interface for the intray app.
description: Please see README.md
category: Intray
author: Tom Sydney Kerckhove & Nick Van den Broeck
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017-2018 Tom Sydney Kerckhove'
license: AllRightsReserved
github: NorfairKing/intray-cli

library:
  source-dirs: src/
  ghc-options: -Wall
  default-extensions:
  - NoImplicitPrelude

  dependencies:
  - aeson >=1.0
  - aeson-pretty >=0.8
  - base >=4.9 && <5
  - bytestring >=0.10
  - containers
  - cookie >=0.4
  - envparse
  - filelock
  - http-client >=0.5
  - http-client-tls >=0.3
  - intray-api
  - intray-client
  - intray-data
  - mergeless
  - mtl >=2.2
  - optparse-applicative >=0.13
  - path >=0.4
  - path-io >=1.2
  - pretty-relative-time
  - servant >=0.9
  - servant-auth-client >=0.2
  - servant-auth-server >=0.3
  - servant-client >=0.9
  - servant-server >=0.9
  - text >=1.2
  - time
  - unliftio
  - validity
  - yaml >=0.8
  - yamlparse-applicative

executables:
  intray:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - intray-cli

tests:
  intray-cli-test:
    main: Spec.hs
    source-dirs: test/
    build-tools: sydtest-discover
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - async
    - base
    - bytestring
    - genvalidity-path
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - intray-api
    - intray-api-gen
    - intray-cli
    - intray-client
    - intray-data
    - intray-server-gen
    - mergeless
    - mtl
    - path
    - path-io
    - servant
    - servant-client
    - sydtest
    - text >=1.2
