snapshot: lts-11.9
packages:
- intray-api
- intray-api-gen
- intray-cli
- intray-client
- intray-data
- intray-data-gen
- intray-server
- intray-server-test-utils
- intray-web-server
extra-deps:
- hlint-2.0.15
- extra-1.6.5
- jose-0.6.0.3
- cookie-0.4.3
- servant-auth-0.3.1.0
- servant-auth-client-0.3.2.0
- servant-auth-docs-0.2.9.0
- servant-auth-server-0.3.2.0
- servant-flatten-0.2
- servant-options-0.1.0.0
- github: NorfairKing/yesod-static-remote
  commit: 22c0a92c1d62f1b8d432003844ef0636a9131b08
- github: NorfairKing/stripe
  commit: ab23e8d5a7232d81d818095fad3fd361fbd485dd
  subdirs:
    - stripe-core
    - stripe-haskell
    - stripe-http-client
    - stripe-http-streams
- github: NorfairKing/mergeless
  commit: 3d5f4b54cc2c4c8c6f33a716bc6b67f376b8d1d5
  subdirs:
    - mergeless
    - genvalidity-mergeless
- github: NorfairKing/validity
  commit: a0fcd782138dac7200e6544c2f40208649ecb0e9
  subdirs:
    - validity
    - validity-bytestring
    - validity-containers
    - validity-path
    - validity-text
    - validity-time
    - validity-uuid
    - genvalidity
    - genvalidity-bytestring
    - genvalidity-containers
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-path
    - genvalidity-property
    - genvalidity-text
    - genvalidity-time
    - genvalidity-uuid
- github: NorfairKing/typed-uuid
  commit: 4c5739c5e231b1cee6bd568ec55734116691ac8f
  subdirs:
    - typed-uuid
    - genvalidity-typed-uuid
- github: NorfairKing/pretty-relative-time
  commit: 2abdb2ba83ad47b8369e2ef618c7c21b82d80b23
nix:
  packages: [zlib]
