snapshot: lts-14.25
packages:
- intray-api
- intray-api-gen
- intray-cli
- intray-client
- intray-data
- intray-data-gen
- intray-server
- intray-server-test-utils
- intray-web-server
extra-deps:
- github: haskell-servant/servant
  commit: 5998429e8178c9e9cc58ec3cfdc4d92e0e9c2400
  subdirs:
  - servant
  - servant-client
  - servant-client-core
  - servant-conduit
  - servant-docs
  - servant-foreign
  - servant-server
- github: haskell-servant/servant-auth
  commit: 23971e889f8cbe8790305bda8915f00aa8be5ad9
  subdirs:
  - servant-auth
  - servant-auth-client
  - servant-auth-docs
  - servant-auth-server
  - servant-auth-swagger
- github: haskell-servant/servant-swagger
  commit: be1dd4c4c84543dfe6408f7987b1dc11437cc7ae
- servant-flatten-0.2@sha256:276896f7c5cdec5b8f8493f6205fded0cc602d050b58fdb09a6d7c85c3bb0837,1234

- github: NorfairKing/yesod-static-remote
  commit: 22c0a92c1d62f1b8d432003844ef0636a9131b08
- github: NorfairKing/stripe
  commit: 7ced8cef1e932d3fb222dfb3c79c25595cdc82ab
  subdirs:
    - stripe-core
    - stripe-haskell
    - stripe-http-client
    - stripe-http-streams
- github: NorfairKing/mergeless
  commit: bf61e179d1935282fd32a85121613d2b98a927d9
  subdirs:
    - mergeless
    - genvalidity-mergeless
- github: NorfairKing/validity
  commit: be40c0a0b0bf6a1d58f4a6a5c6770c4a544c4450
  subdirs:
  - genvalidity
  - genvalidity-aeson
  - genvalidity-bytestring
  - genvalidity-containers
  - genvalidity-criterion
  - genvalidity-hspec
  - genvalidity-hspec-aeson
  - genvalidity-hspec-binary
  - genvalidity-hspec-cereal
  - genvalidity-hspec-hashable
  - genvalidity-hspec-optics
  - genvalidity-path
  - genvalidity-property
  - genvalidity-scientific
  - genvalidity-text
  - genvalidity-time
  - genvalidity-unordered-containers
  - genvalidity-uuid
  - genvalidity-vector
  - validity
  - validity-aeson
  - validity-bytestring
  - validity-containers
  - validity-path
  - validity-primitive
  - validity-scientific
  - validity-text
  - validity-time
  - validity-unordered-containers
  - validity-uuid
  - validity-vector
- github: NorfairKing/typed-uuid
  commit: 4c5739c5e231b1cee6bd568ec55734116691ac8f
  subdirs:
    - typed-uuid
    - genvalidity-typed-uuid
- github: NorfairKing/pretty-relative-time
  commit: fc62907b36f6f7348d6ae0e97aceb4d41039d57b
- github: NorfairKing/looper
  commit: 929a8ad6a99a84624767bd9d619cc5318c6bda56

nix:
  path: [ "nixpkgs=https://github.com/NixOS/nixpkgs/archive/323fe92057bb38475a446ff5e18d3b388c2e4403.tar.gz" ]
  add-gc-roots: true
  pure: true
  packages:
  - zlib
  - unzip
  - haskellPackages.autoexporter
  - procps
