name: intray-server
version: '0.0.0.0'
synopsis: Intray Server
description: Please see README.md
category: Intray
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2016-2018 Tom Sydney Kerckhove'
license: AllRightsReserved
github: NorfairKing/intray-server

dependencies:
- base >=4.7 && <5

library:
  source-dirs: src
  ghc-options: -Wall
  default-extensions:
  - NoImplicitPrelude
  dependencies:
  - aeson
  - aeson-pretty
  - async
  - bytestring
  - cache
  - conduit
  - containers
  - envparse
  - exceptions
  - file-embed
  - intray-api
  - intray-data
  - jose
  - markdown
  - mergeless
  - mergeless-persistent
  - monad-logger
  - mtl >=2.2
  - optparse-applicative >=0.13
  - unordered-containers
  - microlens
  - path
  - path-io
  - persistent >=2.7
  - persistent-sqlite
  - pretty-show
  - resourcet
  - safe
  - servant
  - servant-auth-server
  - servant-docs
  - servant-server
  - stripe-api
  - text
  - time
  - typed-uuid
  - wai
  - wai-cors
  - warp >=3.2
  - yaml
  - yamlparse-applicative

executables:
  intray-server:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - intray-server
