name: intray-data-gen
version: '0.0.0.0'
synopsis: Generators for intray-data
category: Intray
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017-2018 Tom Sydney Kerckhove'
license: AllRightsReserved
github: NorfairKing/intray-server

library:
  source-dirs: src
  ghc-options: -Wall

  dependencies:
  - QuickCheck
  - base >=4.7 && <5
  - bytestring
  - genvalidity >=1.0
  - genvalidity-bytestring
  - genvalidity-text
  - genvalidity-time
  - genvalidity-typed-uuid
  - genvalidity-uuid
  - intray-data
  - text
  - validity
  - validity-bytestring
  - validity-text
  - validity-time

tests:
  intray-data-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-text
    - sydtest
    - intray-data
    - intray-data-gen
    - QuickCheck
    - text
    - bytestring
