name: intray-data
version: '0.0.0.0'
synopsis: Intray Data
category: Intray
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017-2018 Tom Sydney Kerckhove'
license: AllRightsReserved
github: NorfairKing/intray

dependencies:
- base >=4.7 && <5

default-extensions:
- NoImplicitPrelude

library:
  source-dirs: src
  ghc-options: -Wall

  dependencies:
  - aeson
  - autodocodec
  - base16-bytestring
  - bcrypt
  - bytestring
  - containers
  - hashable
  - persistent
  - persistent-template
  - random
  - stripe-core
  - stripe-haskell
  - text
  - time
  - typed-uuid
  - uuid
  - validity
  - validity-bytestring
  - validity-containers
  - validity-text
  - validity-time
  - validity-uuid
