name: intray-data
version: '0.0.0.0'
synopsis: Intray Data
category: Intray
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017-2018 Tom Sydney Kerckhove'
license: AllRightsReserved
github: NorfairKing/intray
default-extensions:
- NoImplicitPrelude

dependencies:
- base >=4.7 && <5

library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Intray.Data
  - Intray.Data.AccessKeySecret
  - Intray.Data.AccessKeyUUID
  - Intray.Data.AccountUUID
  - Intray.Data.HashedPassword
  - Intray.Data.ItemType
  - Intray.Data.ItemUUID
  - Intray.Data.UUID
  - Intray.Data.Username

  dependencies:
  - aeson
  - bcrypt
  - bytestring
  - containers
  - hashable
  - persistent
  - persistent-template
  - random
  - base16-bytestring
  - text
  - time
  - typed-uuid
  - uuid
  - validity
  - validity-bytestring
  - stripe-core
  - stripe-haskell
  - validity-containers
  - validity-text
  - validity-time
  - validity-uuid
