name: intray-data
version: '0.0.0.0'
synopsis: Intray Data

dependencies:
- base >=4.7 && <5

default-extensions:
- NoImplicitPrelude

library:
  source-dirs: src

  dependencies:
  - aeson
  - autodocodec
  - base16-bytestring
  - bcrypt
  - bytestring
  - containers
  - hashable
  - http-api-data
  - path-pieces
  - persistent
  - persistent-template
  - random
  - text
  - time
  - typed-uuid
  - uuid
  - validity
  - validity-bytestring
  - validity-containers
  - validity-text
  - validity-time
  - validity-uuid
